import { Country } from './types';

export const COUNTRIES: Country[] = [
  { code: 'US', name: 'USA', emoji: '🇺🇸', color: '#3C3B6E' },
  { code: 'CN', name: 'China', emoji: '🇨🇳', color: '#DE2910' },
  { code: 'IN', name: 'India', emoji: '🇮🇳', color: '#FF9933' },
  { code: 'BR', name: 'Brazil', emoji: '🇧🇷', color: '#009739' },
  { code: 'GB', name: 'UK', emoji: '🇬🇧', color: '#012169' },
  { code: 'FR', name: 'France', emoji: '🇫🇷', color: '#0055A4' },
  { code: 'DE', name: 'Germany', emoji: '🇩🇪', color: '#DD0000' },
  { code: 'JP', name: 'Japan', emoji: '🇯🇵', color: '#BC002D' },
  { code: 'CA', name: 'Canada', emoji: '🇨🇦', color: '#FF0000' },
  { code: 'AU', name: 'Australia', emoji: '🇦🇺', color: '#00008B' },
  { code: 'IT', name: 'Italy', emoji: '🇮🇹', color: '#008C45' },
  { code: 'ES', name: 'Spain', emoji: '🇪🇸', color: '#AA151B' },
  { code: 'KR', name: 'South Korea', emoji: '🇰🇷', color: '#003478' },
  { code: 'RU', name: 'Russia', emoji: '🇷🇺', color: '#D52B1E' },
  { code: 'MX', name: 'Mexico', emoji: '🇲🇽', color: '#006847' },
  { code: 'ID', name: 'Indonesia', emoji: '🇮🇩', color: '#FF0000' },
  { code: 'TR', name: 'Turkey', emoji: '🇹🇷', color: '#C8102E' },
  { code: 'SA', name: 'Saudi Arabia', emoji: '🇸🇦', color: '#165D31' },
  { code: 'CH', name: 'Switzerland', emoji: '🇨🇭', color: '#FF0000' },
  { code: 'SE', name: 'Sweden', emoji: '🇸🇪', color: '#006AA7' },
  { code: 'NG', name: 'Nigeria', emoji: '🇳🇬', color: '#008751' },
  { code: 'PL', name: 'Poland', emoji: '🇵🇱', color: '#DC143C' },
  { code: 'AR', name: 'Argentina', emoji: '🇦🇷', color: '#75AADB' },
  { code: 'BE', name: 'Belgium', emoji: '🇧🇪', color: '#FFCD00' },
  { code: 'TH', name: 'Thailand', emoji: '🇹🇭', color: '#A51931' },
  { code: 'IE', name: 'Ireland', emoji: '🇮🇪', color: '#FF8200' },
  { code: 'NO', name: 'Norway', emoji: '🇳🇴', color: '#BA0C2F' },
  { code: 'IL', name: 'Israel', emoji: '🇮🇱', color: '#0038B8' },
  { code: 'SG', name: 'Singapore', emoji: '🇸🇬', color: '#EF3340' },
  { code: 'DK', name: 'Denmark', emoji: '🇩🇰', color: '#C60C30' },
  { code: 'MY', name: 'Malaysia', emoji: '🇲🇾', color: '#010066' },
  { code: 'VN', name: 'Vietnam', emoji: '🇻🇳', color: '#DA251D' },
  { code: 'PH', name: 'Philippines', emoji: '🇵🇭', color: '#0038A8' },
  { code: 'ZA', name: 'South Africa', emoji: '🇿🇦', color: '#007A4D' },
  { code: 'NZ', name: 'New Zealand', emoji: '🇳🇿', color: '#00247D' },
  { code: 'EG', name: 'Egypt', emoji: '🇪🇬', color: '#CE1126' },
  { code: 'PK', name: 'Pakistan', emoji: '🇵🇰', color: '#115740' },
  { code: 'CL', name: 'Chile', emoji: '🇨🇱', color: '#DA291C' },
  { code: 'FI', name: 'Finland', emoji: '🇫🇮', color: '#003580' },
  { code: 'GR', name: 'Greece', emoji: '🇬🇷', color: '#0D5EAF' },
  { code: 'PT', name: 'Portugal', emoji: '🇵🇹', color: '#FF0000' },
  { code: 'UA', name: 'Ukraine', emoji: '🇺🇦', color: '#005BBB' },
  { code: 'KZ', name: 'Kazakhstan', emoji: '🇰🇿', color: '#00AFCA' },
  { code: 'DZ', name: 'Algeria', emoji: '🇩🇿', color: '#006233' },
  { code: 'CO', name: 'Colombia', emoji: '🇨🇴', color: '#FCD116' },
  { code: 'KE', name: 'Kenya', emoji: '🇰🇪', color: '#BB0000' },
  { code: 'BD', name: 'Bangladesh', emoji: '🇧🇩', color: '#F42A41' },
  { code: 'VE', name: 'Venezuela', emoji: '🇻🇪', color: '#FCD116' },
  { code: 'PE', name: 'Peru', emoji: '🇵🇪', color: '#D91023' },
  { code: 'CZ', name: 'Czechia', emoji: '🇨🇿', color: '#11457E' },
];

export const PHYSICS_CONFIG = {
  ENGINE_FPS: 60,
  WALL_THICKNESS: 40,
  FLAG_RADIUS: 14,
  RING_RADIUS_FACTOR: 0.38, // % of screen min dimension
  RING_ROTATION_SPEED: 0.005,
  GAP_SIZE_DEGREES: 60,
};